<?php

namespace Database\Seeders;

use App\Enums\ListingCategory;
use App\Models\Listing;
use App\Models\ListingImage;
use App\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use RuntimeException;
use Symfony\Component\Finder\SplFileInfo;

class ListingSeeder extends Seeder
{
    /**
     * Listings assigned to each user in id order (20 users, 100 listings).
     *
     * @var list<int>
     */
    private const OWNER_COUNTS = [10, 9, 8, 8, 7, 6, 6, 5, 5, 5, 5, 5, 4, 4, 4, 3, 3, 1, 1, 1];

    /**
     * Seed a varied Teziutlán catalog for filter work.
     */
    public function run(): void
    {
        $users = User::query()->orderBy('id')->get();
        $owners = $this->owners($users);

        foreach ($this->listings() as $index => $listing) {
            $factory = Listing::factory()->for($owners[$index]);

            $factory = match ($listing['type']) {
                'room' => $factory->room(),
                'house' => $factory->house(),
                default => $factory->apartment(),
            };

            if ($listing['unpublished'] ?? false) {
                $factory = $factory->unpublished();
            }

            $model = $factory->create([
                ...$listing['attributes'],
                'published_at' => now()->subDays($index),
            ]);

            $this->attachSeedImages($model, ($index % 5) + 1);
        }
    }

    /**
     * @param  Collection<int, User>  $users
     * @return list<User>
     */
    private function owners(Collection $users): array
    {
        $owners = [];

        foreach (self::OWNER_COUNTS as $index => $count) {
            for ($i = 0; $i < $count; $i++) {
                $owners[] = $users[$index];
            }
        }

        return $owners;
    }

    /**
     * @return list<array{type: string, unpublished?: bool, attributes: array<string, mixed>}>
     */
    private function listings(): array
    {
        return [
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento luminoso en Centro',
                    'description' => 'Departamento de dos recámaras a una cuadra del zócalo. Iluminación natural, cocina integral y agua constante.',
                    'zone' => 'Centro',
                    'street_address' => 'Hidalgo 24',
                    'rent_amount' => 7200,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto en El Carmen',
                    'description' => 'Habitación independiente con baño propio. Ideal para una persona. Incluye internet.',
                    'zone' => 'El Carmen',
                    'street_address' => null,
                    'rent_amount' => 1700,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => false,
                ],
            ],
            [
                'type' => 'house',
                'unpublished' => true,
                'attributes' => [
                    'title' => 'Casa amplia en Francia (no publicada)',
                    'description' => 'Casa de tres recámaras con patio y cochera. Tranquila, cerca de escuelas.',
                    'zone' => 'Francia',
                    'street_address' => 'Privada las Palmas 8',
                    'rent_amount' => 12000,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento amueblado en Aire Libre',
                    'description' => 'Listo para habitar: cama, refrigerador y estufa. Se aceptan mascotas pequeñas.',
                    'zone' => 'Aire Libre',
                    'street_address' => 'Av. México 112',
                    'rent_amount' => 6500,
                    'bedrooms' => 1,
                    'bathrooms' => 1,
                    'is_furnished' => true,
                    'pets_allowed' => true,
                    'include_gas' => true,
                    'include_electricity' => true,
                ],
            ],
            [
                'type' => 'room',
                'unpublished' => true,
                'attributes' => [
                    'title' => 'Cuarto con baño compartido en Xoloco',
                    'description' => 'Cuarto amueblado en casa familiar. Baño y cocina compartidos. Ambiente tranquilo.',
                    'zone' => 'Xoloco',
                    'street_address' => null,
                    'rent_amount' => 1500,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa de cuatro recámaras en El Fresnillo',
                    'description' => 'Ideal para familia. Jardín, dos plantas y espacio para dos autos.',
                    'zone' => 'El Fresnillo',
                    'street_address' => 'Camino Real 45',
                    'rent_amount' => 15000,
                    'bedrooms' => 4,
                    'bathrooms' => 3,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento familiar en La Magdalena',
                    'description' => 'Tres recámaras, sala-comedor amplia y balcón. Sin estacionamiento.',
                    'zone' => 'La Magdalena',
                    'street_address' => 'Morelos 67',
                    'rent_amount' => 7800,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'contact_via_whatsapp' => false,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto independiente en Chignaulingo',
                    'description' => 'Entrada independiente y baño propio. Cerca de transporte. Solo llamadas.',
                    'zone' => 'Chignaulingo',
                    'street_address' => 'Calle 5 de Mayo s/n',
                    'rent_amount' => 1900,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'contact_via_whatsapp' => false,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa amueblada en El Carmen',
                    'description' => 'Se renta amueblada por temporada larga. Patio trasero y cochera techada.',
                    'zone' => 'El Carmen',
                    'street_address' => null,
                    'rent_amount' => 14000,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => true,
                    'pets_allowed' => true,
                    'include_internet' => true,
                    'include_cable' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Estudio céntrico en Centro',
                    'description' => 'Ideal para una o dos personas. Cocina compacta y clóset. Agua 24 horas.',
                    'zone' => 'Centro',
                    'street_address' => 'Juárez 9',
                    'rent_amount' => 4800,
                    'bedrooms' => 1,
                    'bathrooms' => 1,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'house',
                'unpublished' => true,
                'attributes' => [
                    'title' => 'Casa de dos recámaras en El Fresnillo (no publicada)',
                    'description' => 'Planta baja, patio de servicio y tinaco propio. Sin cochera.',
                    'zone' => 'El Fresnillo',
                    'street_address' => 'Andador 3, lote 12',
                    'rent_amount' => 8000,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento con vista en Chignaulingo',
                    'description' => 'Segundo piso, dos recámaras y estacionamiento. Cerca de comercios.',
                    'zone' => 'Chignaulingo',
                    'street_address' => 'Blvd. las Américas 210',
                    'rent_amount' => 6200,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Habitación amueblada en Centro',
                    'description' => 'Cama individual, escritorio y clóset. Cocina compartida. Ideal para estudiante.',
                    'zone' => 'Centro',
                    'street_address' => 'Allende 18',
                    'rent_amount' => 1650,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_water' => true,
                    'include_electricity' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento nuevo en El Carmen',
                    'description' => 'Recién remodelado. Dos recámaras, cocina integral y tinaco. Sin mascotas.',
                    'zone' => 'El Carmen',
                    'street_address' => 'Callejón del Carmen 5',
                    'rent_amount' => 7500,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => false,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_gas' => true,
                ],
            ],
            [
                'type' => 'house',
                'unpublished' => true,
                'attributes' => [
                    'title' => 'Casa con jardín en Aire Libre (no publicada)',
                    'description' => 'Tres recámaras, patio grande y cuarto de servicio. Pendiente de fotos finales.',
                    'zone' => 'Aire Libre',
                    'street_address' => 'Privada del Sol 3',
                    'rent_amount' => 13500,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto amplio en Francia',
                    'description' => 'Ventana al patio, baño propio y espacio para escritorio. Se aceptan mascotas chicas.',
                    'zone' => 'Francia',
                    'street_address' => null,
                    'rent_amount' => 1850,
                    'is_furnished' => true,
                    'pets_allowed' => true,
                    'include_internet' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => false,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento de tres recámaras en El Fresnillo',
                    'description' => 'Tercer piso, sala amplia y cocina con barra. Cerca de la secundaria.',
                    'zone' => 'El Fresnillo',
                    'street_address' => 'Calle San Juan 88',
                    'rent_amount' => 8000,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_water' => true,
                    'include_internet' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa de una planta en La Magdalena',
                    'description' => 'Dos recámaras, patio de servicio y portón eléctrico. Tranquila.',
                    'zone' => 'La Magdalena',
                    'street_address' => 'Andador las Flores 11',
                    'rent_amount' => 9000,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'unpublished' => true,
                'attributes' => [
                    'title' => 'Departamento en Xoloco (no publicado)',
                    'description' => 'Una recámara y estudio. Aún se está pintando. Disponible pronto.',
                    'zone' => 'Xoloco',
                    'street_address' => 'Calle 16 de Septiembre 40',
                    'rent_amount' => 4200,
                    'bedrooms' => 1,
                    'bathrooms' => 1,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto con entrada propia en Francia',
                    'description' => 'Planta alta, baño propio y mini refrigerador. Incluye internet y agua.',
                    'zone' => 'Francia',
                    'street_address' => 'Camino a San Sebastián 22',
                    'rent_amount' => 2000,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa familiar en Xoloco',
                    'description' => 'Cuatro recámaras, dos baños y cochera para dos autos. Patio trasero.',
                    'zone' => 'Xoloco',
                    'street_address' => 'Av. Progreso 150',
                    'rent_amount' => 14500,
                    'bedrooms' => 4,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                    'include_gas' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento económico en Chignaulingo',
                    'description' => 'Dos recámaras, cocina sencilla y lavadero. Renta accesible.',
                    'zone' => 'Chignaulingo',
                    'street_address' => null,
                    'rent_amount' => 4500,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Habitación en El Fresnillo',
                    'description' => 'Casa de huéspedes, baño compartido y cocina común. Ambiente familiar.',
                    'zone' => 'El Fresnillo',
                    'street_address' => 'Lote 7, manzana 2',
                    'rent_amount' => 1400,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_electricity' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa moderna en Chignaulingo',
                    'description' => 'Tres recámaras, sala a doble altura y cochera techada. Recién pintada.',
                    'zone' => 'Chignaulingo',
                    'street_address' => 'Cerrada las Américas 14',
                    'rent_amount' => 14800,
                    'bedrooms' => 3,
                    'bathrooms' => 3,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_cable' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento céntrico de una recámara',
                    'description' => 'A dos cuadras del mercado. Balcón pequeño y clóset empotrado.',
                    'zone' => 'Centro',
                    'street_address' => 'Reforma 33',
                    'rent_amount' => 5200,
                    'bedrooms' => 1,
                    'bathrooms' => 1,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_water' => true,
                    'include_gas' => true,
                ],
            ],
            [
                'type' => 'room',
                'unpublished' => true,
                'attributes' => [
                    'title' => 'Cuarto en El Carmen (no publicado)',
                    'description' => 'Se está cambiando el colchón. Disponible la próxima semana.',
                    'zone' => 'El Carmen',
                    'street_address' => null,
                    'rent_amount' => 1600,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa de dos plantas en Francia',
                    'description' => 'Cinco recámaras, patio interior y espacio para tres autos. Ideal para familia grande.',
                    'zone' => 'Francia',
                    'street_address' => 'Calle Francia 19',
                    'rent_amount' => 15000,
                    'bedrooms' => 5,
                    'bathrooms' => 3,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                    'include_electricity' => false,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento amueblado en Aire Libre',
                    'description' => 'Dos recámaras, sala con sofá y cocina equipada. Listo para mudarse.',
                    'zone' => 'Aire Libre',
                    'street_address' => 'Av. Independencia 77',
                    'rent_amount' => 6800,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => true,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_gas' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto para estudiante en El Fresnillo',
                    'description' => 'Cerca de escuelas. Escritorio, cama y baño compartido. Incluye internet.',
                    'zone' => 'El Fresnillo',
                    'street_address' => 'Calle 2 de Abril 6',
                    'rent_amount' => 1450,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_electricity' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => false,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa sencilla en Xoloco',
                    'description' => 'Dos recámaras, patio chico y tinaco. Buen precio para pareja.',
                    'zone' => 'Xoloco',
                    'street_address' => 'Callejón Xoloco 9',
                    'rent_amount' => 7000,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => false,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento con balcón en La Magdalena',
                    'description' => 'Dos recámaras, vista a la calle y estacionamiento en planta baja.',
                    'zone' => 'La Magdalena',
                    'street_address' => 'Calle Magdalena 21',
                    'rent_amount' => 7000,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_cable' => true,
                ],
            ],
            [
                'type' => 'room',
                'unpublished' => true,
                'attributes' => [
                    'title' => 'Cuarto en La Magdalena (no publicado)',
                    'description' => 'Se está reparando la ventana. Amueblado, baño propio.',
                    'zone' => 'La Magdalena',
                    'street_address' => null,
                    'rent_amount' => 1750,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa con cochera en Chignaulingo',
                    'description' => 'Tres recámaras, cocina amplia y patio de lavado. Portón corrido.',
                    'zone' => 'Chignaulingo',
                    'street_address' => 'Carretera a Mexcalcuautla km 1',
                    'rent_amount' => 10500,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento de planta baja en Aire Libre',
                    'description' => 'Tres recámaras y patio chico. Ideal si no quieres escaleras.',
                    'zone' => 'Aire Libre',
                    'street_address' => 'Privada San Sebastián 4',
                    'rent_amount' => 7600,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => false,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_gas' => true,
                    'include_electricity' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Habitación independiente en Chignaulingo',
                    'description' => 'Entrada por el costado de la casa. Baño propio y clóset grande.',
                    'zone' => 'Chignaulingo',
                    'street_address' => 'Blvd. las Américas 88',
                    'rent_amount' => 1950,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'contact_via_whatsapp' => false,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa céntrica de tres recámaras',
                    'description' => 'A cinco minutos del zócalo. Patio interior y local comercial abajo (no incluido).',
                    'zone' => 'Centro',
                    'street_address' => 'Calle 5 de Mayo 14',
                    'rent_amount' => 12500,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => false,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento nuevo en Francia',
                    'description' => 'Dos recámaras, cocina integral y cisterna. Fraccionamiento cerrado.',
                    'zone' => 'Francia',
                    'street_address' => 'Cerrada Trinidad 7',
                    'rent_amount' => 7700,
                    'bedrooms' => 2,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto amueblado en Aire Libre',
                    'description' => 'Cama matrimonial, buró y ventilador. Baño compartido con otra habitación.',
                    'zone' => 'Aire Libre',
                    'street_address' => null,
                    'rent_amount' => 1550,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_electricity' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'house',
                'unpublished' => true,
                'attributes' => [
                    'title' => 'Casa de tres recámaras en La Magdalena (no publicada)',
                    'description' => 'Tres recámaras y jardín. El dueño aún vive ahí unas semanas.',
                    'zone' => 'La Magdalena',
                    'street_address' => 'Calle Magdalena 30',
                    'rent_amount' => 11800,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Loft en Centro cerca del zócalo',
                    'description' => 'Espacio abierto, cocina americana y baño completo. Ideal para una pareja.',
                    'zone' => 'Centro',
                    'street_address' => 'Portal Hidalgo 2',
                    'rent_amount' => 5800,
                    'bedrooms' => 1,
                    'bathrooms' => 1,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_cable' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto luminoso en Francia',
                    'description' => 'Segundo piso, mucha luz y baño propio. Se renta a persona sola.',
                    'zone' => 'Francia',
                    'street_address' => 'Privada Francia 2',
                    'rent_amount' => 1800,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_gas' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa de tres recámaras en El Carmen',
                    'description' => 'Barrio tranquilo. Patio, tinaco y espacio para un auto afuera.',
                    'zone' => 'El Carmen',
                    'street_address' => 'Calle del Carmen 41',
                    'rent_amount' => 11000,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento de dos recámaras en El Fresnillo',
                    'description' => 'Primer piso, cocina con estufa y refrigerador. Se aceptan mascotas.',
                    'zone' => 'El Fresnillo',
                    'street_address' => null,
                    'rent_amount' => 6400,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => false,
                    'is_furnished' => true,
                    'pets_allowed' => true,
                    'include_gas' => true,
                    'include_electricity' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Habitación con baño propio en Aire Libre',
                    'description' => 'Casa de dos niveles; el cuarto está en planta baja. Incluye internet y agua.',
                    'zone' => 'Aire Libre',
                    'street_address' => 'Calle Aire Libre 15',
                    'rent_amount' => 1880,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_water' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'house',
                'unpublished' => true,
                'attributes' => [
                    'title' => 'Casa en La Magdalena (no publicada)',
                    'description' => 'Dos recámaras y local anexo. Se publicará cuando terminen la bardita.',
                    'zone' => 'La Magdalena',
                    'street_address' => 'Calle Morelos 102',
                    'rent_amount' => 9800,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento amplio en Xoloco',
                    'description' => 'Tres recámaras, dos baños y lavandería. Buena ventilación.',
                    'zone' => 'Xoloco',
                    'street_address' => 'Calle Xoloco 27',
                    'rent_amount' => 7300,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => false,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                    'include_internet' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento de una recámara en Xoloco',
                    'description' => 'Planta alta, cocina compacta y clóset. Para una o dos personas.',
                    'zone' => 'Xoloco',
                    'street_address' => null,
                    'rent_amount' => 3000,
                    'bedrooms' => 1,
                    'bathrooms' => 1,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_gas' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto en casa familiar en El Carmen',
                    'description' => 'Reglas de convivencia claras. Cocina y sala compartidas. Solo no fumadores.',
                    'zone' => 'El Carmen',
                    'street_address' => 'Calle Progreso 8',
                    'rent_amount' => 1480,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_electricity' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento con estacionamiento en El Fresnillo',
                    'description' => 'Dos recámaras, segundo piso y cajón techado. Agua constante.',
                    'zone' => 'El Fresnillo',
                    'street_address' => 'Andador 1, lote 4',
                    'rent_amount' => 5500,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_water' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => false,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento familiar en Chignaulingo',
                    'description' => 'Tres recámaras, patio de tendedero y cerca de transporte público.',
                    'zone' => 'Chignaulingo',
                    'street_address' => 'Calle Principal 55',
                    'rent_amount' => 7100,
                    'bedrooms' => 3,
                    'bathrooms' => 1,
                    'has_parking' => false,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                    'include_gas' => true,
                    'include_electricity' => false,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento en planta alta en Centro',
                    'description' => 'Segundo piso, una recámara y cocina con barra. A tres cuadras del zócalo.',
                    'zone' => 'Centro',
                    'street_address' => 'Calle Independencia 16',
                    'rent_amount' => 5600,
                    'bedrooms' => 1,
                    'bathrooms' => 1,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_water' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto cerca del mercado en Centro',
                    'description' => 'Cama individual, clóset y cocina compartida. Ideal para quien trabaja en el centro.',
                    'zone' => 'Centro',
                    'street_address' => 'Aldama 11',
                    'rent_amount' => 1720,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa de dos recámaras en Centro',
                    'description' => 'Planta baja, patio de servicio y tinaco. Caminas al zócalo en diez minutos.',
                    'zone' => 'Centro',
                    'street_address' => 'Calle Colón 28',
                    'rent_amount' => 8500,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => false,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento amueblado en El Carmen',
                    'description' => 'Dos recámaras, sala con sofá y cocina con estufa. Listo para mudarse.',
                    'zone' => 'El Carmen',
                    'street_address' => 'Callejón del Carmen 18',
                    'rent_amount' => 6900,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => false,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_gas' => true,
                    'include_internet' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto con clóset en El Carmen',
                    'description' => 'Habitación amplia, baño propio y espacio para escritorio. Se renta a persona sola.',
                    'zone' => 'El Carmen',
                    'street_address' => null,
                    'rent_amount' => 1820,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => false,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa con patio en El Carmen',
                    'description' => 'Tres recámaras, patio trasero y espacio para un auto. Barrio tranquilo.',
                    'zone' => 'El Carmen',
                    'street_address' => 'Calle del Carmen 55',
                    'rent_amount' => 10200,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'house',
                'unpublished' => true,
                'attributes' => [
                    'title' => 'Casa de dos plantas en El Carmen (no publicada)',
                    'description' => 'Cuatro recámaras y cochera. El dueño aún está empacando.',
                    'zone' => 'El Carmen',
                    'street_address' => 'Privada del Carmen 6',
                    'rent_amount' => 13200,
                    'bedrooms' => 4,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento económico en Francia',
                    'description' => 'Una recámara, cocina sencilla y lavadero. Buena opción para empezar.',
                    'zone' => 'Francia',
                    'street_address' => 'Calle Francia 31',
                    'rent_amount' => 3800,
                    'bedrooms' => 1,
                    'bathrooms' => 1,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto económico en Francia',
                    'description' => 'Baño compartido, cama y buró. Incluye agua y luz. Ambiente familiar.',
                    'zone' => 'Francia',
                    'street_address' => 'Camino a San Sebastián 8',
                    'rent_amount' => 1420,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_water' => true,
                    'include_electricity' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa de una planta en Francia',
                    'description' => 'Dos recámaras, patio chico y portón. Cerca de escuelas.',
                    'zone' => 'Francia',
                    'street_address' => 'Cerrada Trinidad 12',
                    'rent_amount' => 9200,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_gas' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento de una recámara en Francia',
                    'description' => 'Planta baja, clóset empotrado y cocina compacta. Fraccionamiento cerrado.',
                    'zone' => 'Francia',
                    'street_address' => 'Privada las Palmas 14',
                    'rent_amount' => 4100,
                    'bedrooms' => 1,
                    'bathrooms' => 1,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento de dos recámaras en Xoloco',
                    'description' => 'Primer piso, cocina integral y tendedero. Cerca de transporte.',
                    'zone' => 'Xoloco',
                    'street_address' => 'Calle 16 de Septiembre 22',
                    'rent_amount' => 6100,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => false,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                    'include_internet' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Habitación en casa de dos pisos en Xoloco',
                    'description' => 'Cuarto en planta alta, baño compartido y cocina común. Se aceptan mascotas chicas.',
                    'zone' => 'Xoloco',
                    'street_address' => 'Callejón Xoloco 15',
                    'rent_amount' => 1580,
                    'is_furnished' => true,
                    'pets_allowed' => true,
                    'include_internet' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa con jardín en Xoloco',
                    'description' => 'Tres recámaras, jardín delantero y cochera. Ideal para familia.',
                    'zone' => 'Xoloco',
                    'street_address' => 'Av. Progreso 88',
                    'rent_amount' => 11500,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                    'include_gas' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto en segundo piso en Xoloco',
                    'description' => 'Ventana a la calle, baño propio y mini refrigerador. Incluye internet.',
                    'zone' => 'Xoloco',
                    'street_address' => 'Calle Xoloco 41',
                    'rent_amount' => 1680,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'unpublished' => true,
                'attributes' => [
                    'title' => 'Departamento con estacionamiento en Aire Libre (no publicado)',
                    'description' => 'Dos recámaras y cajón techado. Falta terminar la pintura de la sala.',
                    'zone' => 'Aire Libre',
                    'street_address' => 'Av. México 90',
                    'rent_amount' => 7400,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto con baño compartido en Aire Libre',
                    'description' => 'Casa de huéspedes. Cama matrimonial, clóset y cocina común.',
                    'zone' => 'Aire Libre',
                    'street_address' => 'Calle Aire Libre 28',
                    'rent_amount' => 1510,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_electricity' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'house',
                'unpublished' => true,
                'attributes' => [
                    'title' => 'Casa amplia en Aire Libre (no publicada)',
                    'description' => 'Cuatro recámaras y patio grande. Pendiente de trámites del predial.',
                    'zone' => 'Aire Libre',
                    'street_address' => 'Privada San Sebastián 9',
                    'rent_amount' => 13800,
                    'bedrooms' => 4,
                    'bathrooms' => 3,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento sencillo en Aire Libre',
                    'description' => 'Dos recámaras, cocina con lavadero y buena ventilación. Sin mascotas.',
                    'zone' => 'Aire Libre',
                    'street_address' => 'Av. Independencia 41',
                    'rent_amount' => 4700,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_gas' => true,
                    'contact_via_whatsapp' => false,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Mini departamento en El Fresnillo',
                    'description' => 'Estudio con cocina compacta. Para una persona. Agua constante.',
                    'zone' => 'El Fresnillo',
                    'street_address' => 'Calle San Juan 12',
                    'rent_amount' => 3300,
                    'bedrooms' => 1,
                    'bathrooms' => 1,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Habitación independiente en El Fresnillo',
                    'description' => 'Entrada por el patio. Baño propio y clóset. Cerca de escuelas.',
                    'zone' => 'El Fresnillo',
                    'street_address' => 'Camino Real 18',
                    'rent_amount' => 1920,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa familiar en El Fresnillo',
                    'description' => 'Tres recámaras, dos plantas y espacio para dos autos. Patio de lavado.',
                    'zone' => 'El Fresnillo',
                    'street_address' => 'Andador 2, lote 8',
                    'rent_amount' => 12800,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                    'include_electricity' => false,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento remodelado en La Magdalena',
                    'description' => 'Dos recámaras, cocina nueva y balcón. Recién pintado.',
                    'zone' => 'La Magdalena',
                    'street_address' => 'Calle Magdalena 8',
                    'rent_amount' => 6700,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => false,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_gas' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Habitación para pareja en La Magdalena',
                    'description' => 'Cama matrimonial, baño propio y mini cocina. Se renta a pareja sin hijos.',
                    'zone' => 'La Magdalena',
                    'street_address' => 'Andador las Flores 3',
                    'rent_amount' => 1980,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_water' => true,
                    'include_electricity' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa de cuatro recámaras en La Magdalena',
                    'description' => 'Dos plantas, jardín y cochera techada. Ideal para familia grande.',
                    'zone' => 'La Magdalena',
                    'street_address' => 'Calle Morelos 58',
                    'rent_amount' => 14900,
                    'bedrooms' => 4,
                    'bathrooms' => 3,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                    'include_cable' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento con terraza en Chignaulingo',
                    'description' => 'Dos recámaras, terraza chica y estacionamiento. Vista despejada.',
                    'zone' => 'Chignaulingo',
                    'street_address' => 'Blvd. las Américas 44',
                    'rent_amount' => 7200,
                    'bedrooms' => 2,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'room',
                'unpublished' => true,
                'attributes' => [
                    'title' => 'Cuarto amueblado en Chignaulingo (no publicado)',
                    'description' => 'Se está cambiando la cerradura. Cama, escritorio y baño propio.',
                    'zone' => 'Chignaulingo',
                    'street_address' => null,
                    'rent_amount' => 1620,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa sencilla en Chignaulingo',
                    'description' => 'Dos recámaras, patio de servicio y tinaco. Buen precio para pareja.',
                    'zone' => 'Chignaulingo',
                    'street_address' => 'Calle Principal 19',
                    'rent_amount' => 7800,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => false,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento de tres recámaras en El Carmen',
                    'description' => 'Tercer piso, sala-comedor amplia y cocina con barra. Sin estacionamiento.',
                    'zone' => 'El Carmen',
                    'street_address' => 'Calle Progreso 22',
                    'rent_amount' => 7900,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => false,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                    'include_gas' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento familiar en Centro',
                    'description' => 'Tres recámaras, dos baños y cocina integral. A cinco minutos del mercado.',
                    'zone' => 'Centro',
                    'street_address' => 'Reforma 8',
                    'rent_amount' => 8000,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_water' => true,
                    'include_internet' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento compacto en Centro',
                    'description' => 'Una recámara, cocina americana y clóset. Ideal para quien trabaja cerca del zócalo.',
                    'zone' => 'Centro',
                    'street_address' => 'Portal Juárez 5',
                    'rent_amount' => 4300,
                    'bedrooms' => 1,
                    'bathrooms' => 1,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_water' => true,
                    'include_gas' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto amueblado detrás del zócalo',
                    'description' => 'Cama individual, escritorio y baño compartido. Incluye internet.',
                    'zone' => 'Centro',
                    'street_address' => 'Calle 2 Norte 7',
                    'rent_amount' => 1590,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_electricity' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa de tres recámaras cerca del centro',
                    'description' => 'Patio interior, tinaco y espacio para un auto en la calle. Sin amueblar.',
                    'zone' => 'Centro',
                    'street_address' => 'Calle Zaragoza 19',
                    'rent_amount' => 11800,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => false,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento de dos recámaras en El Carmen',
                    'description' => 'Planta alta, cocina integral y lavadero. Barrio tranquilo.',
                    'zone' => 'El Carmen',
                    'street_address' => 'Callejón Hidalgo 3',
                    'rent_amount' => 6300,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => false,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => false,
                ],
            ],
            [
                'type' => 'room',
                'unpublished' => true,
                'attributes' => [
                    'title' => 'Cuarto en El Carmen cerca de la iglesia (no publicado)',
                    'description' => 'Se está cambiando el tinaco. Amueblado, baño propio.',
                    'zone' => 'El Carmen',
                    'street_address' => null,
                    'rent_amount' => 1710,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa de una planta en El Carmen',
                    'description' => 'Dos recámaras, patio de servicio y portón. Ideal para pareja.',
                    'zone' => 'El Carmen',
                    'street_address' => 'Calle 5 de Mayo 42',
                    'rent_amount' => 8800,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_gas' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento amueblado en Francia',
                    'description' => 'Dos recámaras, sala con sofá y cocina equipada. Fraccionamiento cerrado.',
                    'zone' => 'Francia',
                    'street_address' => 'Cerrada las Palmas 5',
                    'rent_amount' => 7100,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => true,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_gas' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Habitación con entrada independiente en Francia',
                    'description' => 'Planta baja, baño propio y clóset. Se renta a persona sola.',
                    'zone' => 'Francia',
                    'street_address' => 'Calle Francia 44',
                    'rent_amount' => 1860,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'house',
                'unpublished' => true,
                'attributes' => [
                    'title' => 'Casa familiar en Francia (no publicada)',
                    'description' => 'Tres recámaras y jardín. El dueño termina de mudarse en dos semanas.',
                    'zone' => 'Francia',
                    'street_address' => 'Privada Trinidad 9',
                    'rent_amount' => 12400,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento económico en Xoloco',
                    'description' => 'Una recámara, cocina sencilla y tendedero. Renta accesible.',
                    'zone' => 'Xoloco',
                    'street_address' => 'Calle 20 de Noviembre 6',
                    'rent_amount' => 3500,
                    'bedrooms' => 1,
                    'bathrooms' => 1,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto para estudiante en Xoloco',
                    'description' => 'Cama, escritorio y cocina compartida. Incluye internet y agua.',
                    'zone' => 'Xoloco',
                    'street_address' => 'Av. Progreso 33',
                    'rent_amount' => 1470,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa de dos plantas en Xoloco',
                    'description' => 'Cuatro recámaras, patio trasero y cochera para dos autos.',
                    'zone' => 'Xoloco',
                    'street_address' => 'Calle Xoloco 60',
                    'rent_amount' => 14200,
                    'bedrooms' => 4,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                    'include_electricity' => false,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento de tres recámaras en Aire Libre',
                    'description' => 'Planta baja, patio chico y cocina con barra. Ideal si no quieres escaleras.',
                    'zone' => 'Aire Libre',
                    'street_address' => 'Privada del Sol 11',
                    'rent_amount' => 7750,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => false,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_gas' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Habitación luminosa en Aire Libre',
                    'description' => 'Segundo piso, mucha luz y baño propio. Se aceptan mascotas chicas.',
                    'zone' => 'Aire Libre',
                    'street_address' => 'Av. México 55',
                    'rent_amount' => 1790,
                    'is_furnished' => true,
                    'pets_allowed' => true,
                    'include_internet' => true,
                    'contact_via_whatsapp' => true,
                    'contact_via_phone' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa sencilla de dos recámaras en Aire Libre',
                    'description' => 'Una planta, tinaco y patio de lavado. Buen precio para pareja.',
                    'zone' => 'Aire Libre',
                    'street_address' => 'Calle Aire Libre 40',
                    'rent_amount' => 7600,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => false,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento de dos recámaras con cajón en El Fresnillo',
                    'description' => 'Dos recámaras, segundo piso y cajón descubierto. Agua constante.',
                    'zone' => 'El Fresnillo',
                    'street_address' => 'Calle 2 de Abril 21',
                    'rent_amount' => 5900,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_water' => true,
                    'include_internet' => true,
                ],
            ],
            [
                'type' => 'room',
                'attributes' => [
                    'title' => 'Cuarto en casa familiar en El Fresnillo',
                    'description' => 'Reglas de convivencia claras. Cocina compartida. Solo no fumadores.',
                    'zone' => 'El Fresnillo',
                    'street_address' => 'Lote 11, manzana 3',
                    'rent_amount' => 1440,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_internet' => true,
                    'include_water' => true,
                    'include_electricity' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento de una recámara en La Magdalena',
                    'description' => 'Planta alta, cocina compacta y balcón. Para una o dos personas.',
                    'zone' => 'La Magdalena',
                    'street_address' => 'Calle Magdalena 44',
                    'rent_amount' => 3900,
                    'bedrooms' => 1,
                    'bathrooms' => 1,
                    'is_furnished' => false,
                    'pets_allowed' => false,
                    'include_gas' => true,
                ],
            ],
            [
                'type' => 'house',
                'attributes' => [
                    'title' => 'Casa con cochera en La Magdalena',
                    'description' => 'Tres recámaras, cocina amplia y portón corrido. Barrio familiar.',
                    'zone' => 'La Magdalena',
                    'street_address' => 'Calle Morelos 73',
                    'rent_amount' => 10900,
                    'bedrooms' => 3,
                    'bathrooms' => 2,
                    'has_parking' => true,
                    'is_furnished' => false,
                    'pets_allowed' => true,
                    'include_water' => true,
                    'include_cable' => true,
                ],
            ],
            [
                'type' => 'apartment',
                'attributes' => [
                    'title' => 'Departamento de dos recámaras en Chignaulingo',
                    'description' => 'Primer piso, cocina con estufa y refrigerador. Cerca de transporte.',
                    'zone' => 'Chignaulingo',
                    'street_address' => 'Calle Principal 72',
                    'rent_amount' => 5400,
                    'bedrooms' => 2,
                    'bathrooms' => 1,
                    'has_parking' => false,
                    'is_furnished' => true,
                    'pets_allowed' => false,
                    'include_gas' => true,
                    'include_electricity' => true,
                    'contact_via_whatsapp' => false,
                    'contact_via_phone' => true,
                ],
            ],
        ];
    }

    private function attachSeedImages(Listing $listing, int $count): void
    {
        $fixtures = $this->fixturePaths($listing->category);

        for ($position = 0; $position < $count; $position++) {
            $fixture = $fixtures[($listing->id + $position) % count($fixtures)];
            $path = 'listings/'.$listing->id.'/'.Str::uuid().'.jpg';
            Storage::disk(ListingImage::DISK)->put($path, File::get($fixture));

            ListingImage::factory()->for($listing)->create([
                'path' => $path,
                'disk' => ListingImage::DISK,
                'position' => $position,
                'is_cover' => $position === 0,
            ]);
        }
    }

    /**
     * @return list<string>
     */
    private function fixturePaths(ListingCategory $category): array
    {
        $directory = database_path('seeders/fixtures/listings/'.$category->value);
        $paths = collect(File::files($directory))
            ->filter(fn (SplFileInfo $file): bool => $file->getExtension() === 'jpg')
            ->map(fn (SplFileInfo $file): string => $file->getPathname())
            ->values()
            ->all();

        if ($paths === []) {
            throw new RuntimeException('Missing listing image fixtures in '.$directory);
        }

        return $paths;
    }
}
